### ISSUE TITLE
Long URL must be valid URL.

### ISSUE THREAD

**Issue by rajkharvar** [xprilion/fireshort#7]
**Describe the bug**
Long URL must be valid URL else app will go in an inconsistent (infinite-loop) state. Currently, the user can add any text in a long URL.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Admin Panel
2. Click on the add button
3. Add long URL which is not valid URL something like test and Short URL like test.
4. Now click open on the added link.

**Expected behaviour**
Long URL must be validated before adding.

**Additional context**
This problem can be solved by using validator which checks for the long URL (valid or not) before adding.

**Comment by ashuvssut** [comment]
I want to work on this issue

**Comment by xprilion** [comment]
@ashuvssut sure! How do you plan to solve this? Please mention a brief and an expected time you're planning to spend on this issue :)

**Comment by ashuvssut** [comment]
I am already working on this issue.

I will use nodejs dns.resolve() to check if the domain really exist/existed.

This is best than using fetch or xhr because:-

1. Even if (after a dns probe) I get a statuscode 500...the users get to add the shorturl. I want this behaviour because sometimes a webserver might be in maintenance mode and hence giving a 512 status code or something.
Since the server exists I will allow the user to add the url in the app.

2. I can't use fetch or xhr because fireShort is cleint side... So if I ping a url to check if it exists or not , I will get a CORS error.


So the best way to do this is using nodejs dns.resolve()

Expected time to complete:- 3 days or less

**Comment by xprilion** [comment]
Sounds good, go ahead!
